### ISSUE TITLE
añadir una interfaz en español + tema oscuro 

### ISSUE THREAD

**Issue by JaneRemover** [Fmaldonado6/Akiyama#19]
me gustaría que la aplicación fuera más personalizable, ya que tiene mucho potencial. Es una de las pocas aplicaciones de streaming de anime en español que se ve y se siente bien. Con un poco más de personalización (y opciones para poder descargar si es posible?), esto sería increíble (aunque lo es de todas maneras); no sé programar, y además esta es la primera vez que utilizamos GitHub, así que estoy dejando este comentario como una recomendación

muchas gracias!

**Comment by Fmaldonado6** [comment]
Hola muchas gracias por tus comentarios los tendré en cuenta!! Solo para avisar la app sí cuenta con modo oscuro y se activa en automático al activar el modo oscuro de su teléfono, si esto no es así por favor hagamelo saber

**Comment by JaneRemover** [comment]
> Hola muchas gracias por tus comentarios los tendré en cuenta!! Solo para avisar la app sí cuenta con modo oscuro y se activa en automático al activar el modo oscuro de su teléfono, si esto no es así por favor hagamelo saber
